### ISSUE TITLE
where is the loss of DQI component?I cannot find it, and why only retrieve loss is used in training?

### ISSUE THREAD

**Issue by cipolee** [liyongqi67/DGRCoQA#1]

**Comment by liyongqi67** [comment]
Thanks for your question. The DQI loss is the "retriever_loss". The DQI component is trained via the question-document pair. (Sorry, I just saw your issue because my Github email is tied to too many other apps and there is a lot of junk email.)

**Comment by liyongqi67** [comment]
The different components are trained separately. The current version needs to manually change the final loss to train different components.

**Comment by cipolee** [comment]
OK! Thanks!
